Iter13
iliamikado/UrlShortener pull request #13
Opened 2024-03-19 18:41 UTC by iliamikado

2024-03-21 10:25 UTC, valentinsoe requested changes
Спасибо за работу.

Глобально замечание одно - бесконечный цикл при записи в БД нескольких ссылок.
Если это способ проверки "уникальности" сгененрированных коротких ссылок - то он очень неудачен и неэффективен:)

2024-03-21 10:25 UTC, valentinsoe commented on cmd/shortener/main.go
> +	if (config.DatabaseDsn != "") {
Просто для чистоты кода - я бы рекомендовал сделать отдельную функцию. Будет значительно удобнее читать.

2024-03-21 10:25 UTC, valentinsoe commented on internal/db/db.go
> +		id text PRIMARY KEY NOT NULL,
А где поле UUID, которое в файл писали?:)

2024-03-21 10:25 UTC, valentinsoe commented on internal/db/db.go
> +		stmt.Exec(ids[i], longURLs[i])
Лучше все-таки проверять на наличие ошибок и делать Rollback сразу.

2024-03-21 10:25 UTC, valentinsoe commented on internal/storage/dbStorage.go
> +	for {
Зачем здесь бесконечный цикл?

2024-03-21 10:25 UTC, valentinsoe commented on internal/storage/dbStorage.go
> +			ids[i] = randomID();
Кажется логика проверки уникальности сгенерированного идентификатора здесь утерялась.

2024-03-22 15:25 UTC, iliamikado commented on cmd/shortener/main.go
> +	if (config.DatabaseDsn != "") {
сделал

2024-03-22 15:26 UTC, iliamikado commented on internal/db/db.go
> +		id text PRIMARY KEY NOT NULL,
У меня назывался просто id, и не было shortURL (как в файле). Переименовал в uuid  и добавил shortURL

2024-03-22 15:26 UTC, iliamikado commented on internal/db/db.go
> +		stmt.Exec(ids[i], longURLs[i])
сделал

2024-03-22 15:29 UTC, iliamikado commented on internal/storage/dbStorage.go
> +	for {
для создания уникального id. Убрал это отсюда и теперь делаю это во время транзакции (а не несколько транзакций, пока все Id не будут уникальны)

2024-03-22 15:29 UTC, iliamikado commented on internal/storage/dbStorage.go
> +			ids[i] = randomID();
исправлено

2024-03-25 23:13 UTC, valentinsoe approved these changes
Спасибо за исправления.
Написал комментарии. Они к исправлению не супер критичны, но как пища для подумать будут полезны.

2024-03-25 23:13 UTC, valentinsoe commented on internal/db/db.go
> +			shortURL := config.ResultAddress + "/" + ids[i];
Хранить в базе "полный" short URL не очень хорошая затея.
Если завтра наш сервис запустят по другому адресу(с другим ResultAddress) - это все сломает:)

2024-03-25 23:13 UTC, valentinsoe commented on internal/db/db.go
> +	for i := 0; i < len(longURLs); i++ {
В целом пойдет. Но я бы рекомендовал упростить эту историю до следующего:
Вероятность сгенерировать неуникальный ID крайне невелика. Можно просто клиенту отдать ошибку.:)
У нас тут внутри транзакции все равно бесконечный цикл - что делает тразнацию потенциально очень медленной

2024-03-26 07:37 UTC, merged