Iter15
iliamikado/UrlShortener pull request #15
Opened 2024-04-02 14:56 UTC by iliamikado

2024-04-02 23:01 UTC, valentinsoe requested changes
Спасибо за работу!
Комментарии в PR.
Из того, что обязательно надо исправить - надо сделать по заданию обработку неверной куки и также сделать асинхронное удаление. А не синхронное, мучающее БД в множество потоков.

2024-04-02 23:01 UTC, valentinsoe commented on internal/db/db.go
> +		if !isDeleted {
Проще это условие доверить SQL. Не будем скачивать из БД лишние данные и обрабатывать их на уровне приложения.

2024-04-02 23:01 UTC, valentinsoe commented on internal/db/db.go
> +		g.Go(func() error {
За что базе такое наказание? Удалять каждую запись отдельной горутиной?
В задании сказано наоборот - накапливать и удалять батчем:)

2024-04-02 23:01 UTC, valentinsoe commented on internal/handlers/authMiddleware.go
> +			userID = urlStorage.CreateNewUser()
В случае получения некорректной куки - мы должны возвращать ошибку по заданию, а не игнорировать и ставить новую.

2024-04-02 23:01 UTC, valentinsoe commented on internal/handlers/authMiddleware.go
> +			userID = urlStorage.CreateNewUser()
Если генерировать usedId как UUID, то можно не создавать отдельную таблицу и не усложнять себе жизнь лишними запросами.

2024-04-02 23:01 UTC, valentinsoe commented on internal/handlers/handlers.go
> +	c, err := r.Cookie("JWT")
А зачем мы положили userId в контекст, чтобы снова разбирать куку?

2024-04-02 23:01 UTC, valentinsoe commented on internal/db/db.go
> +		g.Go(func() error {
Более того - использовать 1 транзакцию в нескольких горутинах - небезопасно

2024-04-03 08:01 UTC, iliamikado commented on internal/handlers/authMiddleware.go
> +			userID = urlStorage.CreateNewUser()
Это для одной ручки - getUsersURLs. Ее я отдельно проверяю. Для ручек POST, надо создавать куку, если ее нет или она не валидна. (данная мидлвара как раз только на этих ручках и используется)

2024-04-03 08:02 UTC, iliamikado commented on internal/handlers/handlers.go
> +	c, err := r.Cookie("JWT")
Здесь не клал. Тут отдельная логика, так что в этой ручки authMiddleware не используется

2024-04-03 08:02 UTC, iliamikado commented on internal/handlers/authMiddleware.go
> +			userID = urlStorage.CreateNewUser()
ок, сделал

2024-04-03 08:02 UTC, iliamikado commented on internal/db/db.go
> +		if !isDeleted {
сделал

2024-04-03 08:03 UTC, iliamikado commented on internal/db/db.go
> +		g.Go(func() error {
исправил...

2024-04-05 23:37 UTC, valentinsoe commented on internal/handlers/authMiddleware.go
> +			userID = urlStorage.CreateNewUser()
Для всех ручек надо создавать куку. И было бы неплохо для всех же ее и проверять(единообразно).

2024-04-05 23:38 UTC, valentinsoe commented on internal/handlers/handlers.go
> +	c, err := r.Cookie("JWT")
А почему она в ней не используется?

2024-04-05 23:45 UTC, valentinsoe approved these changes
Спасибо за работу. Комментарии написал по коду.
Из того над чем рекомендую подумать - это как выполнить все-таки удаление асинхронно с буферизацией(как написано в советах в задании инкремента)

2024-04-05 23:45 UTC, valentinsoe commented on internal/db/db.go
> +	query := fmt.Sprintf("update urls set is_deleted = true where user_id = $1 and uuid in (%s)", strings.Join(valueStrings, ","))
Опасная практика так форматировать параметры.
Можно использовать во такой синтаксис:
`.... where uuid = any ($1)`, pq.Array(valueStrings)

2024-04-08 13:56 UTC, merged